export const baseCategoryIncomeDataEng = [
  'Salary',
  'Stipend',
  'Pension',
  'Business',
  'Sales',
  'Award',
  'Lottery',
  'Other',
];

export const baseCategoryIncomeDataRu = [
  'Заработная плата',
  'Стипендия',
  'Пенсия',
  'Бизнес',
  'Продажи',
  'Премия',
  'Лотерея',
  'Прочее',
];

export const baseCategoryExpenditureDataEng = [
  'Transport',
  'BarsAndRestaurants',
  'Alcohol',
  'EatingOut',
  'Food',
  'Health',
  'Entertainment',
  'Presents',
  'Regular',
  'Clothing',
  'BankingServices',
  'Other',
];

export const baseCategoryExpenditureDataRu = [
  'Транспорт',
  'Бары и рестораны',
  'Алкоголь',
  'Еда вне дома',
  'Продукты',
  'Здоровье',
  'Развлечения',
  'Подарки',
  'Регулярные',
  'Одежда',
  'Банковские операции',
  'Прочее',
];

export const baseExpenseCategoryColor = {
  Transport: '#ef4444',
  Транспорт: '#ef4444',
  Barsandrestaurants: '#3b82f6',
  Барыирестораны: '#3b82f6',
  Alcohol: '#10b981',
  Алкоголь: '#10b981',
  Eatingout: '#a855f7',
  Едавнедома: '#a855f7',
  Food: '#f59e0b',
  Продукты: '#f59e0b',
  Health: '#3b82f6',
  Здоровье: '#3b82f6',
  Entertainment: '#ef4444',
  Развлечения: '#ef4444',
  Presents: '#3b82f6',
  Подарки: '#3b82f6',
  Regular: '#10b981',
  Регулярные: '#10b981',
  Clothing: '#a855f7',
  Одежда: '#a855f7',
  Bankingservices: '#f59e0b',
  Банковскиеоперации: '#f59e0b',
  Other: '#3b82f6',
  Прочее: '#3b82f6',
};

export const baseIncomeCategoryColor = {
  Salary: '#ef4444',
  Заработнаяплата: '#ef4444',
  Stipend: '#3b82f6',
  Стипендия: '#3b82f6',
  Pension: '#10b981',
  Пенсия: '#10b981',
  Business: '#a855f7',
  Бизнес: '#a855f7',
  Sales: '#f59e0b',
  Продажи: '#f59e0b',
  Award: '#3b82f6',
  Премия: '#3b82f6',
  Lottery: '#ef4444',
  Лотерея: '#ef4444',
  Other: '#3b82f6',
  Прочее: '#3b82f6',
};
