// const testTransactions = [
//   {
//     type: 'expense',
//     category: 'mobile',
//     subcategory: 'tele2',
//     description: 'апрель',
//     data: '1',
//     time: '1',
//     sum: 70,
//     userId: 2,
//     id: 1,
//   },
//   {
//     type: 'income',
//     category: 'mobile',
//     subcategory: 'mts',
//     description: 'апрель',
//     data: '06/02/2023',
//     time: '17:38',
//     sum: 80,
//     userId: '4',
//     id: 2,
//   },
//   {
//     type: 'income',
//     category: 'mobile',
//     subcategory: 'mts',
//     description: 'апрель',
//     data: '06/02/2023',
//     time: '12:38',
//     sum: 400,
//     userId: '4',
//     id: 3,
//   },
//   {
//     type: 'income',
//     category: 'mobile',
//     subcategory: 'mts',
//     description: 'апрель',
//     data: '11/01/2023',
//     time: '15:38',
//     sum: 1000,
//     userId: '4',
//     id: 4,
//   },
//   {
//     type: 'expense',
//     category: 'home',
//     subcategory: 'water',
//     description: 'апрель',
//     data: '12/09/2022',
//     time: '16:36',
//     sum: 200,
//     userId: 4,
//     id: 5,
//   },
//   {
//     type: 'expense',
//     category: 'car',
//     subcategory: 'break',
//     description: 'апрель авария сбил муху и расстроился',
//     data: '06/01/2023',
//     time: '11:30',
//     sum: 900,
//     userId: 4,
//     id: 5,
//   },
//   {
//     type: 'expense',
//     category: 'product',
//     subcategory: 'teeth',
//     description: 'сломала зуб',
//     data: '01/02/2023',
//     time: '15:35',
//     sum: 1100,
//     userId: 4,
//     id: 5,
//   },
//   {
//     type: 'expense',
//     category: 'home',
//     subcategory: 'water',
//     description: 'апрель',
//     data: '13/01/2023',
//     time: '23:38',
//     sum: 50,
//     userId: 4,
//     id: 5,
//   },
// ];

// const settings = [
//   {
//     lang: 'en',
//     theme: 'light',
//     currency: 'usd',
//     name: 'Вася',
//     userId: '2',
//     id: 6,
//   },
// ];
